all: install

install:
	install -p -b -m 755 -D boot/firmware/config-cs10600ra070-$(LARCH).txt /boot/firmware/config-cs10600ra070.txt
	install -p -m 755 -D boot/firmware/config-cs10600ra070-$(LARCH).txt $(TP)/boot/firmware/config-cs10600ra070.txt
	install -p -b -m 755 -D boot/firmware/config-cs12800ra101-$(LARCH).txt /boot/firmware/config-cs12800ra101.txt
	install -p -m 755 -D boot/firmware/config-cs12800ra101-$(LARCH).txt $(TP)/boot/firmware/config-cs12800ra101.txt
	install -p -b -m 755 -D boot/firmware/config-cs12800ra4101box-$(LARCH).txt /boot/firmware/config-cs12800ra4101box.txt
	install -p -m 755 -D boot/firmware/config-cs12800ra4101box-$(LARCH).txt $(TP)/boot/firmware/config-cs12800ra4101box.txt
	# CM4
	install -p -b -m 755 -D boot/firmware/config-cs12800ra4101a-$(LARCH).txt /boot/firmware/config-cs12800ra4101a.txt
	install -p -m 755 -D boot/firmware/config-cs12800ra4101a-$(LARCH).txt $(TP)/boot/firmware/config-cs12800ra4101a.txt
	install -p -b -m 755 -D boot/firmware/config-cs12800ra4101av4-$(LARCH).txt /boot/firmware/config-cs12800ra4101av4.txt
	install -p -m 755 -D boot/firmware/config-cs12800ra4101av4-$(LARCH).txt $(TP)/boot/firmware/config-cs12800ra4101av4.txt
	install -p -b -m 755 -D boot/firmware/config-cs12800ra4101p-$(LARCH).txt /boot/firmware/config-cs12800ra4101p.txt
	install -p -m 755 -D boot/firmware/config-cs12800ra4101p-$(LARCH).txt $(TP)/boot/firmware/config-cs12800ra4101p.txt
	install -p -b -m 755 -D boot/firmware/config-cs10600ra4070-$(LARCH).txt /boot/firmware/config-cs10600ra4070.txt
	install -p -m 755 -D boot/firmware/config-cs10600ra4070-$(LARCH).txt $(TP)/boot/firmware/config-cs10600ra4070.txt
	install -p -b -m 755 -D boot/firmware/config-cs10600ra4070d-$(LARCH).txt /boot/firmware/config-cs10600ra4070d.txt
	install -p -m 755 -D boot/firmware/config-cs10600ra4070d-$(LARCH).txt $(TP)/boot/firmware/config-cs10600ra4070d.txt
	install -p -b -m 755 -D boot/firmware/config-cs12720ra4050-$(LARCH).txt /boot/firmware/config-cs12720ra4050.txt
	install -p -m 755 -D boot/firmware/config-cs12720ra4050-$(LARCH).txt $(TP)/boot/firmware/config-cs12720ra4050.txt
	install -p -b -m 755 -D boot/firmware/config-cs10768ra4121p-$(LARCH).txt /boot/firmware/config-cs10768ra4121p.txt
	install -p -m 755 -D boot/firmware/config-cs10768ra4121p-$(LARCH).txt $(TP)/boot/firmware/config-cs10768ra4121p.txt
	install -p -b -m 755 -D boot/firmware/config-cs19108ra4133p-$(LARCH).txt /boot/firmware/config-cs19108ra4133p.txt
	install -p -m 755 -D boot/firmware/config-cs19108ra4133p-$(LARCH).txt $(TP)/boot/firmware/config-cs19108ra4133p.txt
	install -p -b -m 755 -D boot/firmware/config-cs19108ra4133piso-$(LARCH).txt /boot/firmware/config-cs19108ra4133piso.txt
	install -p -m 755 -D boot/firmware/config-cs19108ra4133piso-$(LARCH).txt $(TP)/boot/firmware/config-cs19108ra4133piso.txt
	install -p -b -m 755 -D boot/firmware/config-cs10768ra4150p-$(LARCH).txt /boot/firmware/config-cs10768ra4150p.txt
	install -p -m 755 -D boot/firmware/config-cs10768ra4150p-$(LARCH).txt $(TP)/boot/firmware/config-cs10768ra4150p.txt
	install -p -b -m 755 -D boot/firmware/config-cs19108ra4156p-$(LARCH).txt /boot/firmware/config-cs19108ra4156p.txt
	install -p -m 755 -D boot/firmware/config-cs19108ra4156p-$(LARCH).txt $(TP)/boot/firmware/config-cs19108ra4156p.txt
	install -p -b -m 755 -D boot/firmware/config-cs12102ra4170p-$(LARCH).txt /boot/firmware/config-cs12102ra4170p.txt
	install -p -m 755 -D boot/firmware/config-cs12102ra4170p-$(LARCH).txt $(TP)/boot/firmware/config-cs12102ra4170p.txt
	install -p -b -m 755 -D boot/firmware/config-cs19108ra4185p-$(LARCH).txt /boot/firmware/config-cs19108ra4185p.txt
	install -p -m 755 -D boot/firmware/config-cs19108ra4185p-$(LARCH).txt $(TP)/boot/firmware/config-cs19108ra4185p.txt
	install -p -b -m 755 -D boot/firmware/config-cs12102ra4190p-$(LARCH).txt /boot/firmware/config-cs12102ra4190p.txt
	install -p -m 755 -D boot/firmware/config-cs12102ra4190p-$(LARCH).txt $(TP)/boot/firmware/config-cs12102ra4190p.txt
	install -p -b -m 755 -D boot/firmware/config-cs19108ra4215p-$(LARCH).txt /boot/firmware/config-cs19108ra4215p.txt
	install -p -m 755 -D boot/firmware/config-cs19108ra4215p-$(LARCH).txt $(TP)/boot/firmware/config-cs19108ra4215p.txt
	install -p -b -m 755 -D boot/firmware/config-cs19108ra4236p-$(LARCH).txt /boot/firmware/config-cs19108ra4236p.txt
	install -p -m 755 -D boot/firmware/config-cs19108ra4236p-$(LARCH).txt $(TP)/boot/firmware/config-cs19108ra4236p.txt
	# CM5
	install -p -b -m 755 -D boot/firmware/config-cs12720ra5050p-$(LARCH).txt /boot/firmware/config-cs12720ra5050p.txt
	install -p -m 755 -D boot/firmware/config-cs12720ra5050p-$(LARCH).txt $(TP)/boot/firmware/config-cs12720ra5050p.txt
	install -p -b -m 755 -D boot/firmware/config-cs10600ra5070p-$(LARCH).txt /boot/firmware/config-cs10600ra5070p.txt
	install -p -m 755 -D boot/firmware/config-cs10600ra5070p-$(LARCH).txt $(TP)/boot/firmware/config-cs10600ra5070p.txt
	install -p -b -m 755 -D boot/firmware/config-cs10600ra5070p-d-$(LARCH).txt /boot/firmware/config-cs10600ra5070p-d.txt
	install -p -m 755 -D boot/firmware/config-cs10600ra5070p-d-$(LARCH).txt $(TP)/boot/firmware/config-cs10600ra5070p-d.txt
	install -p -b -m 755 -D boot/firmware/config-cs12800ra5101a-$(LARCH).txt /boot/firmware/config-cs12800ra5101a.txt
	install -p -m 755 -D boot/firmware/config-cs12800ra5101a-$(LARCH).txt $(TP)/boot/firmware/config-cs12800ra5101a.txt
	install -p -b -m 755 -D boot/firmware/config-cs12800ra5101p-$(LARCH).txt /boot/firmware/config-cs12800ra5101p.txt
	install -p -m 755 -D boot/firmware/config-cs12800ra5101p-$(LARCH).txt $(TP)/boot/firmware/config-cs12800ra5101p.txt
	install -p -b -m 755 -D boot/firmware/config-cs10768ra5121p-$(LARCH).txt /boot/firmware/config-cs10768ra5121p.txt
	install -p -m 755 -D boot/firmware/config-cs10768ra5121p-$(LARCH).txt $(TP)/boot/firmware/config-cs10768ra5121p.txt
	install -p -b -m 755 -D boot/firmware/config-cs19108ra5133p-$(LARCH).txt /boot/firmware/config-cs19108ra5133p.txt
	install -p -m 755 -D boot/firmware/config-cs19108ra5133p-$(LARCH).txt $(TP)/boot/firmware/config-cs19108ra5133p.txt
	install -p -b -m 755 -D boot/firmware/config-cs10768ra5150p-$(LARCH).txt /boot/firmware/config-cs10768ra5150p.txt
	install -p -m 755 -D boot/firmware/config-cs10768ra5150p-$(LARCH).txt $(TP)/boot/firmware/config-cs10768ra5150p.txt
	install -p -b -m 755 -D boot/firmware/config-cs19108ra5156p-$(LARCH).txt /boot/firmware/config-cs19108ra5156p.txt
	install -p -m 755 -D boot/firmware/config-cs19108ra5156p-$(LARCH).txt $(TP)/boot/firmware/config-cs19108ra5156p.txt
	install -p -b -m 755 -D boot/firmware/config-cs12102ra5170p-$(LARCH).txt /boot/firmware/config-cs12102ra5170p.txt
	install -p -m 755 -D boot/firmware/config-cs12102ra5170p-$(LARCH).txt $(TP)/boot/firmware/config-cs12102ra5170p.txt
	install -p -b -m 755 -D boot/firmware/config-cs19108ra5185p-$(LARCH).txt /boot/firmware/config-cs19108ra5185p.txt
	install -p -m 755 -D boot/firmware/config-cs19108ra5185p-$(LARCH).txt $(TP)/boot/firmware/config-cs19108ra5185p.txt
	install -p -b -m 755 -D boot/firmware/config-cs12102ra5190p-$(LARCH).txt /boot/firmware/config-cs12102ra5190p.txt
	install -p -m 755 -D boot/firmware/config-cs12102ra5190p-$(LARCH).txt $(TP)/boot/firmware/config-cs12102ra5190p.txt
	install -p -b -m 755 -D boot/firmware/config-cs19108ra5215p-$(LARCH).txt /boot/firmware/config-cs19108ra5215p.txt
	install -p -m 755 -D boot/firmware/config-cs19108ra5215p-$(LARCH).txt $(TP)/boot/firmware/config-cs19108ra5215p.txt
	install -p -b -m 755 -D boot/firmware/config-cs19108ra5236p-$(LARCH).txt /boot/firmware/config-cs19108ra5236p.txt
	install -p -m 755 -D boot/firmware/config-cs19108ra5236p-$(LARCH).txt $(TP)/boot/firmware/config-cs19108ra5236p.txt
	# Other File
	install -p -b -m 755 -D boot/firmware/config-$(LARCH).txt /boot/firmware/config.txt
	install -p -m 755 -D boot/firmware/config-$(LARCH).txt $(TP)/boot/firmware/config.txt
	# First boot
	install -p -b -m 755 -D boot/firmware/cmdline.txt /boot/firmware/cmdline.txt
	install -p -m 755 -D boot/firmware/cmdline.txt $(TP)/boot/firmware/cmdline.txt
	install -p -b -m 755 -D boot/firmware/firstrun.sh /boot/firmware/firstrun.sh
	install -p -m 755 -D boot/firmware/firstrun.sh $(TP)/boot/firmware/firstrun.sh
	#install -p -b -m 755 -D boot/firmware/userconf /boot/firmware/userconf
	#install -p -m 755 -D boot/firmware/userconf $(TP)/boot/firmware/userconf
	install -p -m 644 -D usr/lib/systemd/system/chipsee-init.service /usr/lib/systemd/system/chipsee-init.service
	install -p -m 644 -D usr/lib/systemd/system/chipsee-init.service $(TP)/usr/lib/systemd/system/chipsee-init.service
	install -p -m 644 -D usr/lib/systemd/user/audioswitch.service /usr/lib/systemd/user/audioswitch.service
	install -p -m 644 -D usr/lib/systemd/user/audioswitch.service $(TP)/usr/lib/systemd/user/audioswitch.service
	install -p -m 644 -D usr/lib/systemd/user/dpms-lcd.service /usr/lib/systemd/user/dpms-lcd.service
	install -p -m 644 -D usr/lib/systemd/user/dpms-lcd.service $(TP)/usr/lib/systemd/user/dpms-lcd.service
	install -p -m 755 -D usr/bin/lcdinit_$(LARCH) /usr/bin/lcdinit
	install -p -m 755 -D usr/bin/lcdinit_$(LARCH) $(TP)/usr/bin/lcdinit
	install -p -m 777 -D opt/chipsee/chipsee-init.sh /opt/chipsee/chipsee-init.sh
	install -p -m 777 -D opt/chipsee/chipsee-init.sh $(TP)/opt/chipsee/chipsee-init.sh
	install -p -m 777 -D opt/chipsee/audioswitch.sh /opt/chipsee/audioswitch.sh
	install -p -m 777 -D opt/chipsee/audioswitch.sh $(TP)/opt/chipsee/audioswitch.sh
	install -p -m 777 -D opt/chipsee/dpms-lcd.sh /opt/chipsee/dpms-lcd.sh
	install -p -m 777 -D opt/chipsee/dpms-lcd.sh $(TP)/opt/chipsee/dpms-lcd.sh
	install -p -m 777 -D opt/chipsee/test/gpiotest.sh /opt/chipsee/test/gpiotest.sh
	install -p -m 777 -D opt/chipsee/test/gpiotest.sh $(TP)/opt/chipsee/test/gpiotest.sh
	install -p -m 777 -D opt/chipsee/test/uarttest.txt /opt/chipsee/test/uarttest.txt
	install -p -m 777 -D opt/chipsee/test/uarttest.txt $(TP)/opt/chipsee/test/uarttest.txt
	install -p -m 777 -D opt/chipsee/tools/bc-aarch64 /opt/chipsee/tools/bc-aarch64
	install -p -m 777 -D opt/chipsee/tools/bc-aarch64 $(TP)/opt/chipsee/tools/bc-aarch64
	install -p -m 777 -D opt/chipsee/tools/bc-armv7l /opt/chipsee/tools/bc-armv7l
	install -p -m 777 -D opt/chipsee/tools/bc-armv7l $(TP)/opt/chipsee/tools/bc-armv7l
	install -p -m 777 -D opt/chipsee/tools/i2c-aarch64/i2cdetect /opt/chipsee/tools/i2c-aarch64/i2cdetect
	install -p -m 777 -D opt/chipsee/tools/i2c-aarch64/i2cdetect $(TP)/opt/chipsee/tools/i2c-aarch64/i2cdetect
	install -p -m 777 -D opt/chipsee/tools/i2c-armv7l/i2cdetect /opt/chipsee/tools/i2c-armv7l/i2cdetect
	install -p -m 777 -D opt/chipsee/tools/i2c-armv7l/i2cdetect $(TP)/opt/chipsee/tools/i2c-armv7l/i2cdetect
	install -p -m 777 -D opt/chipsee/tools/i2c-aarch64/libi2c.so.0 /opt/chipsee/tools/i2c-aarch64/libi2c.so.0
	install -p -m 777 -D opt/chipsee/tools/i2c-aarch64/libi2c.so.0 $(TP)/opt/chipsee/tools/i2c-aarch64/libi2c.so.0
	install -p -m 777 -D opt/chipsee/tools/i2c-armv7l/libi2c.so.0 /opt/chipsee/tools/i2c-armv7l/libi2c.so.0
	install -p -m 777 -D opt/chipsee/tools/i2c-armv7l/libi2c.so.0 $(TP)/opt/chipsee/tools/i2c-armv7l/libi2c.so.0
	install -p -m 777 -D opt/chipsee/test/cantest/canconfig /opt/chipsee/test/cantest/canconfig
	install -p -m 777 -D opt/chipsee/test/cantest/canconfig $(TP)/opt/chipsee/test/cantest/canconfig
	install -p -m 777 -D opt/chipsee/test/cantest/candump /opt/chipsee/test/cantest/candump
	install -p -m 777 -D opt/chipsee/test/cantest/candump $(TP)/opt/chipsee/test/cantest/candump
	install -p -m 777 -D opt/chipsee/test/cantest/canecho /opt/chipsee/test/cantest/canecho
	install -p -m 777 -D opt/chipsee/test/cantest/canecho $(TP)/opt/chipsee/test/cantest/canecho
	install -p -m 777 -D opt/chipsee/test/cantest/cansend /opt/chipsee/test/cantest/cansend
	install -p -m 777 -D opt/chipsee/test/cantest/cansend $(TP)/opt/chipsee/test/cantest/cansend
	install -p -m 777 -D opt/chipsee/test/cantest/cansequence /opt/chipsee/test/cantest/cansequence
	install -p -m 777 -D opt/chipsee/test/cantest/cansequence $(TP)/opt/chipsee/test/cantest/cansequence
	install -p -m 777 -D opt/chipsee/test/cantest/cantest.sh /opt/chipsee/test/cantest/cantest.sh
	install -p -m 777 -D opt/chipsee/test/cantest/cantest.sh $(TP)/opt/chipsee/test/cantest/cantest.sh
	install -p -m 777 -D opt/chipsee/test/cantest/README /opt/chipsee/test/cantest/README
	install -p -m 777 -D opt/chipsee/test/cantest/README $(TP)/opt/chipsee/test/cantest/README
	install -p -m 777 -D opt/chipsee/voicecard/asound_2mic.conf /opt/chipsee/voicecard/asound_2mic.conf
	install -p -m 777 -D opt/chipsee/voicecard/asound_2mic.conf $(TP)/opt/chipsee/voicecard/asound_2mic.conf
	install -p -m 777 -D opt/chipsee/voicecard/wm8960_asound.state /opt/chipsee/voicecard/wm8960_asound.state
	install -p -m 777 -D opt/chipsee/voicecard/wm8960_asound.state $(TP)/opt/chipsee/voicecard/wm8960_asound.state
	# 4G
	install -p -b -m 755 -D  opt/chipsee/test/quectel-linux-4g.tar.gz /opt/chipsee/test/quectel-linux-4g.tar.gz
	install -p -m 755 -D  opt/chipsee/test/quectel-linux-4g.tar.gz $(TP)/opt/chipsee/test/quectel-linux-4g.tar.gz
	install -p -b -m 755 -D  opt/chipsee/test/simcom-linux-4g.tar.gz /opt/chipsee/test/simcom-linux-4g.tar.gz
	install -p -m 755 -D  opt/chipsee/test/simcom-linux-4g.tar.gz $(TP)/opt/chipsee/test/simcom-linux-4g.tar.gz
	#install -p -b -m 755 -D  opt/chipsee/test/linux-ppp-scripts/ip-up /opt/chipsee/test/linux-ppp-scripts/ip-up
	#install -p -m 755 -D  opt/chipsee/test/linux-ppp-scripts/ip-up $(TP)/opt/chipsee/test/linux-ppp-scripts/ip-up
	#install -p -b -m 755 -D  opt/chipsee/test/linux-ppp-scripts/quectel-chat-connect /opt/chipsee/test/linux-ppp-scripts/quectel-chat-connect
	#install -p -m 755 -D  opt/chipsee/test/linux-ppp-scripts/quectel-chat-connect $(TP)/opt/chipsee/test/linux-ppp-scripts/quectel-chat-connect
	#install -p -b -m 755 -D  opt/chipsee/test/linux-ppp-scripts/quectel-chat-disconnect /opt/chipsee/test/linux-ppp-scripts/quectel-chat-disconnect
	#install -p -m 755 -D  opt/chipsee/test/linux-ppp-scripts/quectel-chat-disconnect $(TP)/opt/chipsee/test/linux-ppp-scripts/quectel-chat-disconnect
	#install -p -b -m 755 -D  opt/chipsee/test/linux-ppp-scripts/quectel-ppp /opt/chipsee/test/linux-ppp-scripts/quectel-ppp
	#install -p -m 755 -D  opt/chipsee/test/linux-ppp-scripts/quectel-ppp $(TP)/opt/chipsee/test/linux-ppp-scripts/quectel-ppp
	#install -p -b -m 755 -D  opt/chipsee/test/linux-ppp-scripts/quectel-pppd.sh /opt/chipsee/test/linux-ppp-scripts/quectel-pppd.sh
	#install -p -m 755 -D  opt/chipsee/test/linux-ppp-scripts/quectel-pppd.sh $(TP)/opt/chipsee/test/linux-ppp-scripts/quectel-pppd.sh
	#install -p -b -m 755 -D  opt/chipsee/test/linux-ppp-scripts/quectel-ppp-kill /opt/chipsee/test/linux-ppp-scripts/quectel-ppp-kill
	#install -p -m 755 -D  opt/chipsee/test/linux-ppp-scripts/quectel-ppp-kill $(TP)/opt/chipsee/test/linux-ppp-scripts/quectel-ppp-kill
	#install -p -b -m 755 -D  opt/chipsee/test/linux-ppp-scripts/README /opt/chipsee/test/linux-ppp-scripts/README
	#install -p -m 755 -D  opt/chipsee/test/linux-ppp-scripts/README $(TP)/opt/chipsee/test/linux-ppp-scripts/README
	# csdev
	install -p -m 777 -D usr/bin/csdev_$(LARCH) /usr/bin/csdev
	install -p -m 777 -D usr/bin/csdev_$(LARCH) $(TP)/usr/bin/csdev
	install -p -m 777 -D usr/bin/csdev_$(LARCH) /usr/bin/cspn
	install -p -m 777 -D usr/bin/csdev_$(LARCH) $(TP)/usr/bin/cspn
	install -p -m 777 -D usr/bin/csdev_$(LARCH) /usr/bin/csrev
	install -p -m 777 -D usr/bin/csdev_$(LARCH) $(TP)/usr/bin/csrev
	# transform90
	install -p -b -m 755 -D  etc/transform90.tar.gz /etc/transform90.tar.gz
	install -p -m 755 -D  etc/transform90.tar.gz $(TP)/etc/transform90.tar.gz

	install -p -b -m 755 -D usr/lib/raspberrypi-sys-mods/firstboot /usr/lib/raspberrypi-sys-mods/firstboot
	install -p -m 755 -D usr/lib/raspberrypi-sys-mods/firstboot $(TP)/usr/lib/raspberrypi-sys-mods/firstboot
	systemctl enable chipsee-init.service

clean: install
	systemctl disable chipsee-init.service
	rm /opt/chipsee -rf
	rm /usr/bin/lcdinit
	rm /boot/firmware/config-*.txt
	mv /usr/lib/raspberrypi-sys-mods/firstboot~ /usr/lib/raspberrypi-sys-mods/firstboot
	mv /boot/firmware/config.txt~ /boot/firmware/config.txt
